# Generated by Django 6.1.1 on 2026-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='authority',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
